apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mizuchi-uploadr

commonLabels:
  app.kubernetes.io/name: mizuchi-uploadr
  app.kubernetes.io/component: s3-proxy

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: mizuchi-uploadr-config
    behavior: merge
    files:
      - config.yaml
