apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mizuchi-uploadr
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - uploads.example.com
      secretName: mizuchi-uploadr-tls
  rules:
    - host: uploads.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-mizuchi-uploadr
                port:
                  number: 80
