apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mizuchi-uploadr
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mizuchi-uploadr
      app.kubernetes.io/instance: production
