apiVersion: v1
kind: Service
metadata:
  name: {{ include "mizuchi-uploadr.fullname" . }}
  labels:
    {{- include "mizuchi-uploadr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mizuchi-uploadr.selectorLabels" . | nindent 4 }}
---
{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mizuchi-uploadr.fullname" . }}-metrics
  labels:
    {{- include "mizuchi-uploadr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsService.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "mizuchi-uploadr.selectorLabels" . | nindent 4 }}
{{- end }}
